### ISSUE TITLE
GIT_CLIFF_INCLUDE_PATH not working for multiple values

### ISSUE THREAD

**Issue by chamini2** [orhun/git-cliff#123]
**Describe the bug**

**To Reproduce**
1. clone https://github.com/fal-ai/fal/commit/cb785c00746fcbb4e9d401ebc1e3da6e17759436
2. GIT_CLIFF_INCLUDE_PATH="adapter/*"
3. git cliff shows output
4. GIT_CLIFF_INCLUDE_PATH=".github/*"
5. git cliff shows output
6. GIT_CLIFF_INCLUDE_PATH="adapter/* .github/*"
7. git cliff shows NO output

**Expected behavior**
I expected git cliff to generate changelogs for commits touching ANY of the 2 directories

**Comment by chamini2** [comment]
I cannot use the --include-path flag becuase I cannot get it working: look at https://github.com/orhun/git-cliff-action/pull/3

**Comment by orhun** [comment]
Hmm, have you tried using a comma-separated list for `GIT_CLIFF_INCLUDE_PATH`?

**Comment by orhun** [comment]
I guess this is solved in `git-cliff-action`. Let me know if you're still having problems!

**Comment by sam-stenvall-iceye** [comment]
This doesn't seem to have been resolved. I've tried both space-separated and comma-separated glob patterns, but any combination of two patterns results in an empty change log being generated.

**Comment by ognis1205** [comment]
Thanks for the report @sam-stenvall-iceye !

I confirmed this is still an issue. I believe this is caused by the fact that we don't properly configure the clap env variable delimiter, so multiple values from GIT_CLIFF_INCLUDE_PATH are not parsed as expected.

cc: @orhun

**Comment by sam-stenvall-iceye** [comment]
What worked in the end for me was passing `--include-path` multiple times, e.g. `--include-path 'foo/**/*' --include-path bar.txt`

**Comment by sam-stenvall-iceye** [comment]
@ognis1205 so with the latest fixes, both `--include-path 'foo/*' --include-path 'bar/*'` and `--include-path 'foo/* bar/*'` should work?

**Comment by ognis1205** [comment]
hey @sam-stenvall-iceye ,

yes, I've tested all three approaches:

```sh
export GIT_CLIFF_INCLUDE_PATH="website/**/* .github/**/*"
cargo run
```

```sh
unset GIT_CLIFF_INCLUDE_PATH
cargo run -- --include-path 'website/**/* .github/**/*'
```

```sh
unset GIT_CLIFF_INCLUDE_PATH
cargo run -- --include-path 'website/**/*' --include-path '.github/**/*'
```

All three produced the same result.

**Comment by orhun** [comment]
Are we also testing all those three different cases as test fixtures as well?

If not, we should probably do that :)

**Comment by ognis1205** [comment]
> Are we also testing all those three different cases as test fixtures as well?
> 
> If not, we should probably do that :)

I filed an issue 👍 

https://github.com/orhun/git-cliff/issues/1455
